name: Java build with Gradle and test with JUnit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    env:
      OWNER_USERNAME: ${{ secrets.OWNER_USERNAME }}
      OWNER_TOKEN: ${{ secrets.OWNER_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test project
        working-directory: ${{github.workspace}}
        run: ./gradlew build
